name: Run unit tests

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run tests
        run: yarn install && yarn workspaces run test
